# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Java
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
export PATH=$PATH:$JAVA_HOME/bin

# Maven
export MAVEN_HOME=/usr/local/installs/maven/current
export M2_HOME=/usr/local/installs/maven/current
export MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m -XX:CompileCommand=exclude,com/infusion/databridge/MemoryRst,loadMeta'
export PATH=$PATH:$MAVEN_HOME/bin

# Tomcat 7
export TOMCAT_HOME=/usr/local/installs/tomcat/current
export PATH=$PATH:$TOMCAT_HOME/bin

# Ant
export ANT_HOME=/usr/local/installs/ant/current
export PATH=$PATH:$ANT_HOME/bin

# MySQL
export PATH=$PATH:/usr/local/mysql/bin

export PATH=$PATH:$HOME/bin

# Updates PATH for the Google Cloud SDK.
source '/Users/cade.fassett/google-cloud-sdk/path.zsh.inc'

